# Generated by Django 5.1.7 on 2025-03-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0002_item_price_order_ordered_date_orderitem_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("S", "Shirt"), ("SW", "Sport Wear"), ("OW", "Outwear")],
                default="S",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                default="P",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
