# Generated by Django 5.1.7 on 2025-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0003_item_category_item_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="imgsrc",
            field=models.CharField(default="None", max_length=8128),
            preserve_default=False,
        ),
    ]
