# Generated by Django 5.1.7 on 2025-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0004_item_imgsrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="title_full",
            field=models.CharField(default="None", max_length=8128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("F", "Fruite"),
                    ("V", "vegetables"),
                    ("OW", "Outwear"),
                    ("BB", "Bread and baked goods"),
                    ("DP", "Dairy products"),
                ],
                max_length=2,
            ),
        ),
    ]
