# Generated by Django 5.1.7 on 2025-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0005_item_title_full_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(default="test-product"),
            preserve_default=False,
        ),
    ]
