# Generated by Django 5.1.7 on 2025-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0006_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
