# Generated by Django 5.1.7 on 2025-03-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0007_item_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default="This is a test description."),
            preserve_default=False,
        ),
    ]
