# Generated by Django 5.1.7 on 2025-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djecommerce", "0008_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
